export const JOB_LIST_REQUEST = "JOB_LIST_REQUEST";
export const JOB_LIST_SUCCESS = "JOB_LIST_SUCCESS";
export const JOB_LIST_FAIL = "JOB_LIST_FAIL";

export const JOB_DETAIL_REQUEST = "JOB_DETAIL_REQUEST";
export const JOB_DETAIL_SUCCESS = "JOB_DETAIL_SUCCESS";
export const JOB_DETAIL_FAIL = "JOB_DETAIL_FAIL";

export const JOB_UPDATE_REQUEST = "JOB_UPDATE_REQUEST";
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS";
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";

export const JOB_CREATE_REQUEST = "JOB_CREATE_REQUEST";
export const JOB_CREATE_SUCCESS = "JOB_CREATE_SUCCESS";
export const JOB_CREATE_FAIL = "JOB_CREATE_FAIL";

export const JOB_STAT_REQUEST = "JOB_STAT_REQUEST";
export const JOB_STAT_SUCCESS = "JOB_STAT_SUCCESS";
export const JOB_STAT_FAIL = "JOB_STAT_FAIL";

export const IS_EDITING = "IS_EDITING";
export const NOT_EDITING = "NOT_EDITING";
